### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Anil8753** [desktop/registry-js#121]
I am developing an electron application and I need to access window registry entries.

npm install --save registry-js
It installed successfully but on run time I am getting the following error:

ERROR in ./node_modules/registry-js/build/Release/registry.node 1:2
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

**Comment by shiftkey** [comment]
@Anil8753 my guess is that you're not rebuilding `registry-js` against the right version of Electron you need. Please check out the documentation on ElectronJS and confirm you have it setup right: https://electronjs.org/docs/tutorial/using-native-node-modules

**Comment by shiftkey** [comment]
@Anil8753 there's lots of information missing from this issue:

 - what version of Node did you have installed?
 - what version of Electron are you trying to use it with?
 - what did `npm install` show?

My guess here is that something is not configured correctly and `npm install` is building against the wrong runtime, which leads to the runtime error because it's a different version of V8.

Please open a fresh issue with more information if you'd like further troubleshooting support.

**Comment by adminy** [comment]
I'm facing a similar enough issue:

```
[vite:node-asset] Could not load Z:/project/node_modules/registry-js/build/Release/registry.node?commonjs-proxy (imported by node_modules/registry-js/dist/lib/registry.js): The argument 'path' must be a string or Uint8Array without null bytes. Received '\x00Z:/project/node_modules/registry-js/build/Release/registry.node'
```
